name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Go(lang)
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Setup build dependencies
        run: make setup
      - name: Build application
        run: make build
