name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  check-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Go(lang)
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Check module dependencies
        run: |
          go version
          test -z "$(go mod tidy && git status go.* --porcelain)"
          go mod verify

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Go(lang)
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Run unit tests
        run: go test -v -cover -race ./...
