name: Lint

on:
  push:
  pull_request:

jobs:
  check-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Go(lang)
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - name: Check module dependencies
        run: |
          go version
          test -z "$(go mod tidy && git status go.* --porcelain)"
          go mod verify

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - name: Retrieve golangci-lint version
        run: |
          echo "Version=$(head -n 1 "${GITHUB_WORKSPACE}/.golangci.yml" | tr -d '# ')" >> $GITHUB_OUTPUT
        id: version
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ steps.version.outputs.Version }}
          only-new-issues: true
